name: Build sigsegv-mvm

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        submodules: 'recursive'  # To clone submodules

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Setup python version 3.x

    - name: Install Python packages and AMBuild
      run: |
        python -m pip install --upgrade pip
        # Clone and install AMBuild from source
        git clone https://github.com/alliedmodders/ambuild.git
        cd ambuild
        python -m pip install .

    - name: Install system dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install -y autoconf libtool nasm libiberty-dev:i386 libelf-dev:i386 libboost-dev:i386 \
          libbsd-dev:i386 libunwind-dev:i386 lib32z1-dev libc6-dev-i386 linux-libc-dev:i386 g++-multilib

    - name: Prepare environment
      run: |
        echo 'export PATH=~/.local/bin:$PATH' >> $GITHUB_ENV

    - name: Clone necessary repositories
      run: |
        mkdir -p $HOME/alliedmodders
        cd $HOME/alliedmodders
        git clone --recursive https://github.com/alliedmodders/sourcemod --depth 1 -b 1.11-dev
        git clone https://github.com/alliedmodders/hl2sdk --depth 1 -b sdk2013 hl2sdk-sdk2013
        git clone https://github.com/alliedmodders/hl2sdk --depth 1 -b tf2 hl2sdk-tf2
        git clone https://github.com/alliedmodders/hl2sdk --depth 1 -b css hl2sdk-css
        git clone https://github.com/alliedmodders/metamod-source --depth 1 -b 1.11-dev

    - name: Build udis86 library
      run: |
        cd $HOME/alliedmodders/sigsegv-mvm/libs/udis86
        ./autogen.sh
        ./configure
        make

    - name: Install Lua
      run: |
        cd $HOME/alliedmodders/sigsegv-mvm/libs
        wget https://www.lua.org/ftp/lua-5.4.4.tar.gz
        tar -xf lua-*.tar.gz
        rm lua-*.tar.gz
        mv lua-* lua
        cd lua
        make MYCFLAGS='-m32' MYLDFLAGS='-m32'

    - name: Run build script
      run: |
        cd $HOME/alliedmodders/sigsegv-mvm
        ./autoconfig.sh
        mkdir -p build/release
        cd build/release
        ambuild

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: sigsegv-mvm-build
        path: $HOME/alliedmodders/sigsegv-mvm/build/release/*
