name: Build and Release

on:
  push:
    branches:
      - master

jobs:
  build-and-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Ensures the full history for all branches is available

    - name: Print working directory after checkout
      run: pwd && ls -lah

    - name: Set up Python 3.x
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Specify the Python version

    - name: Install system dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y autoconf libtool nasm libiberty-dev:i386 libelf-dev:i386 libboost-dev:i386 libbsd-dev:i386 libunwind-dev:i386 lib32z1-dev libc6-dev-i386 linux-libc-dev:i386 g++-multilib
        echo "Dependencies installed successfully."

    - name: Clone dependencies
      run: |
        mkdir -p ${{ github.workspace }}/alliedmodders
        cd ${{ github.workspace }}/alliedmodders
        git clone --recursive https://github.com/alliedmodders/sourcemod --depth 1 -b 1.11-dev
        git clone https://github.com/alliedmodders/hl2sdk --depth 1 -b sdk2013 hl2sdk-sdk2013
        git clone https://github.com/alliedmodders/hl2sdk --depth 1 -b tf2 hl2sdk-tf2
        git clone https://github.com/alliedmodders/hl2sdk --depth 1 -b css hl2sdk-css
        git clone https://github.com/alliedmodders/metamod-source --depth 1 -b 1.11-dev
        git clone https://github.com/alliedmodders/ambuild --depth 1
        pip install ${{ github.workspace }}/alliedmodders/ambuild
        echo "All dependencies cloned and AMBuild installed."

    - name: Print alliedmodders directory structure
      run: ls -lah ${{ github.workspace }}/alliedmodders

    - name: Prepare build environment
      run: |
        echo "export PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV
        cd ${{ github.workspace }}/sigsegv-mvm
        git submodule update --init --recursive
        cd libs/udis86
        ./autogen.sh
        ./configure
        make
        cd ../../libs
        wget https://www.lua.org/ftp/lua-5.4.4.tar.gz
        tar -xf lua-5.4.4.tar.gz
        rm lua-5.4.4.tar.gz
        mv lua-5.4.4 lua
        cd lua
        make MYCFLAGS='-m32' MYLDFLAGS='-m32'
        echo "Environment prepared."

    - name: Print sigsegv-mvm directory structure
      run: ls -lah ${{ github.workspace }}/sigsegv-mvm

    - name: Build project
      run: |
        cd ${{ github.workspace }}/sigsegv-mvm
        ./autoconfig.sh
        mkdir -p build/release
        cd build/release
        ambuild
        echo "Project built."

    - name: Execute multibuild for packaging
      run: |
        cd ${{ github.workspace }}/sigsegv-mvm/build/release
        ./multibuild.sh
        echo "Packaging completed."

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: build/release/*.zip
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true  # Set this to false to make the release public automatically
